#!/usr/bin/python
#Ride the bus explanation
print "Ride The Bus"
print "Ride The Bus is a card game, with cards laid out as follows"
print "   X X   (6) "
print "  X X X  (5) "
print " X X X X (4) "
print " X X X X (3) "
print "  X X X  (2) "
print "   X X   (1) "
print "Each X represents a face down card."
print "Users pick a card, starting at row (1)."
print "If the card picked is not a face card (Jack, Queen, King, or Ace), the user advances to the next row."
print "If a face card is picked, the game is over"
print "The goal is to get to end of the six rows without drawing a face card."
